### ISSUE TITLE
Problem with stability

### ISSUE THREAD

**Issue by Zarvoira** [AhmedBhati/video-streaming-with-flask-socketio#2]
its working well but in the server i have to change from 0.0.0.0 to my own ip address,
and its only working for a minute and client output this message
/////////////////////////////500

**Comment by Zarvoira** [comment]
i thought it because the cv2 didn't release any picture that it send and might make the memory full so i add cap.release but still has the same problem and its actually decreasing memory available in the pi im not sure why this happen even after cap.release?

**Comment by AhmedBhati** [comment]
what is your client device and server can you give more details on the error you are facing, because I haven't faced such problems in live streams. As well as talking about memory not being released might not be due to the code because it's not saving the image file.
